### ISSUE TITLE
Unhelpful error message when parsing `wapm.toml` fails

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wapm-cli#224]
### Describe the bug

The error message that gets printed when `wapm` can't parse a `wapm.toml` file give the user no way of fixing the parse error.

Given the following `wapm.toml`:

```toml
[package]
name = "Michael-F-Bryan/cuboid-model"
version = "0.1.0"
description = "A module for generating a cuboid."
license = "MIT or APACHE-2.0"

[[module]]
name = "cuboid-model"
source = "../target/wasm32-unknown-unknown/release/cuboid_model.wasm"
abi = "none"
```

Trying to publish it then says it was unable to parse the `cuboid-model` module, but doesn't actually say what was wrong with the module or how I can fix it.

```console
$ wapm publish --dry-run
Error: Error building package when parsing module "cuboid-model".
```

### Expected behavior

I would expect the `wapm` CLI to tell me why it was unable to build the package. In this case, the error message would probably look like:

```
Error: Error building package when parsing module "cuboid_model".

Caused by:
  0: Invalid "source" value
  1. The path traverses outside of the current directory
```

### Additional context

```console
$ wapm --version
wapm-cli 0.5.1
$ rustc --version --verbose
rustc 1.61.0-nightly (eb82facb1 2022-04-01)
binary: rustc
commit-hash: eb82facb1626166188d49599a3313fc95201f556
commit-date: 2022-04-01
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```
