### ISSUE TITLE
Publishing fails with "Module ruby must have a source that is a file" when the source file exists

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wapm-cli#282]
### Describe the bug

While publishing, the `wapm` CLI errors out with `Error: Module "ruby" must have a source that is a file` even though the module's file exists.

```console
$ wapm -V
wapm-cli 0.5.6

$ rustc --version --verbose
rustc 1.66.0-nightly (57f097ea2 2022-10-01)
binary: rustc
commit-hash: 57f097ea25f2c05f424fc9b9dc50dbd6d399845c
commit-date: 2022-10-01
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Steps to reproduce

For context, this is what my current directory looks like: 

```console
$ tree .
.
├── build-package.sh
├── dist
│   ├── libruby.wasm
│   ├── rb-abi-guest.wit
│   └── ruby.wasm
└── wapm.toml

1 directory, 5 files
```

You can download it from here: [ruby.tar.gz](https://github.com/wasmerio/wapm-cli/files/9714596/ruby.tar.gz)

The `dist/libruby.wasm` file definitely exists

```console
$ file dist/libruby.wasm
dist/libruby.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
```

My `wapm.toml` contains one command (the Ruby CLI) and one library (an interface to the interpreter)

```toml
[package]
# name = "katei/ruby"
name = "Michael-F-Bryan/ruby"
version = "0.1.2"
description = "The Ruby Programming Language"
license = "MIT"
repository = "https://github.com/ruby/ruby.wasm"

[[module]]
name = "ruby-cli"
source = "dist/ruby.wasm"
abi = "wasi"

[[module]]
name = "ruby"
source = "dist/libruby.wasm"
abi = "wasi"
bindings = { wit-exports = "dist/rb-api-guest.wit", wit-bindgen = "0.1.0" }

[[command]]
name = "ruby"
module = "ruby-cli"
```

For good measure, I also reinstalled `wapm` from git (74de1c28).

```console
$ cargo install --git https://github.com/wasmerio/wapm
    Updating git repository `https://github.com/wasmerio/wapm`
  Installing wapm-cli v0.5.6 (https://github.com/wasmerio/wapm#74de1c28)
    Updating crates.io index
  ...
$ wapm --version
wapm-cli 0.5.6
```

However, trying to do a dry-run publish still fails

```console
$ wapm publish --dry-run
Error: Module "ruby" must have a source that is a file.
```

### Expected behavior

I would expect this to publish like normal.

### Actual behavior

Publishing fails with `Error: Module "ruby" must have a source that is a file.`.
