### ISSUE TITLE
Context on wapm-cli features

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wapm-cli#287]
Current wapm-cli features:

```toml
[features]
default = ["full","packagesigning", "sqlite-bundled"]
sqlite-bundled = ["rusqlite/bundled"]
telemetry = ["sentry"]
update-notifications= ["billboard", "colored"]
prehash-module = ["hex", "blake3"]
packagesigning = []#[cfg(feature = "full")]
integration_tests = ["maplit", "wapm-toml/integration_tests"]
full = [ "dirs", "rusqlite", "prettytable-rs", "reqwest" ]
```

Analysis on code feature flags:
`sqlite-bundled`: it helped on using `sqlite` in macOS M1
`telemetry`: to add sentry monitoring
`update-notifications`: to check on the background when wasmer has a new version (this can be probably removed / always on or based on config)
`prehash-module`: it can probably be removed since it doesn't add that much value and can be always included (doesn't add that much code size)
`packagesigning`: it can probably be removed and be always on
`integration_tests`: it should be removed.

This leaves the only following feature flags:
* `sqlite-bundled`: since it's to solve a macOS M1 issue when using sqlite
* `telemetry`: we need to think if we want this to be always on or based on config instead
