### ISSUE TITLE
Incorrectly fills the ABI field when it is missing

### ISSUE THREAD

**Issue by xmclark** [wasmerio/wapm-cli#99]
wapm-cli incorrectly fills the ABI field when it is missing. This causes the ABI to be set to None when not explicitly set for WASI projects.

To re-create issue:
Create a rust project that targets WASI. Create the wapm toml below. Install a new dependnecy with `wapm-cli` e.g. `wapm install sqlite`

```toml
[package]
name = "mackenzie/pkg"
version = "0.1.1"
description = "hey this is a cool package"

[[module]]
name = "pkg_mod"
source = "./target/wasm32-unknown-wasi/release/pkg.wasm"
```

After install, The toml will updated to include the dependency, and the module will be updated to include the ABI field with the default of None. This is incorrect because the module is actually a WASI module.
